// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD_a1TbISwA1BCXWf9AovOLoTjRZzJdyU',
    appId: '1:381332273218:web:afb6965936f393fb45d5db',
    messagingSenderId: '381332273218',
    projectId: 'englishlearningapp-ed593',
    authDomain: 'englishlearningapp-ed593.firebaseapp.com',
    storageBucket: 'englishlearningapp-ed593.firebasestorage.app',
    measurementId: 'G-039MVEM6J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZpzlmNwHHyTLIL5pW_6JV6g838dbv0ns',
    appId: '1:381332273218:android:6212c41287a6128245d5db',
    messagingSenderId: '381332273218',
    projectId: 'englishlearningapp-ed593',
    storageBucket: 'englishlearningapp-ed593.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD_a1TbISwA1BCXWf9AovOLoTjRZzJdyU',
    appId: '1:381332273218:web:caf2cb8a7f415f8245d5db',
    messagingSenderId: '381332273218',
    projectId: 'englishlearningapp-ed593',
    authDomain: 'englishlearningapp-ed593.firebaseapp.com',
    storageBucket: 'englishlearningapp-ed593.firebasestorage.app',
    measurementId: 'G-Z8TGT1Y7P2',
  );
}
